apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=keycloak-oidc
        - --oidc-issuer-url=http://keycloak.default.svc.cluster.local/TestRealm
        - --skip-oidc-discovery=true
        - --oidc-jwks-url=http://keycloak.default.svc.cluster.local/realms/TestRealm/protocol/openid-connect/certs
        - --redeem-url=http://keycloak.default.svc.cluster.local/realms/TestRealm/protocol/openid-connect/token
        - --login-url=http://keycloak.localtest.me/realms/TestRealm/protocol/openid-connect/auth

        - --redirect-url=http://localtest.me/oauth2/callback
        - --upstream=http://spring-server-service.default.svc.cluster.local:8090

        - --insecure-oidc-skip-issuer-verification=true #For local testing without dns server

        - --email-domain=*
        - --scope=openid email
        #- --pass-authorization-header=true
        #- --pass-access-token=true
        #- --pass-user-headers=true
        #- --set-authorization-header=true
        #- --set-xauthrequest=true
        #- --cookie-refresh=1m
        #- --cookie-expire=30m
        - --http-address=0.0.0.0:4180
        - --cookie-secure=false
        #- --ssl-insecure-skip-verify=true
        #- --ssl-upstream-insecure-skip-verify=true
        #- --skip-auth-route=.*
        #- --api-route=.*
        - --allowed-group=/groups #Limit to allowed groups
        - --insecure-oidc-allow-unverified-email #Nessesary for testing
        - --show-debug-on-error=true #Nessesary for testing
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: oauthproxy
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: clientSecretCode
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: ODlxNVpUMWF1YmhuR0J1Vkl3cStxUT09
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy